config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'main#index'
  get '/about'=>'main#about', as: 'about'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  get '/state/:state' => 'states#show', as: :state
  get 'top-promises' => 'top_promises#index'


  resources :candidates, :only => [:show, :index] do
    resources :promises, :only => [:show, :new, :create] do
      member do
        get :vote_up
        get :vote_down
      end
    end
  end
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  belongs_to :political_party
  has_many :promises

  validates_presence_of :name, :biography, :age
  validates :age, numericality: { greater_than_or_equal_to: 18, less_than_or_equal_to: 100 }
  validates :political_office, inclusion: {in: :political_office_enum}
  validates :state, inclusion: {in: :state_enum, :allow_nil => true}

  mount_uploader :image, CandidateImageUploader

  scope :per_state, lambda { |state| where(:state => state).where('political_office != ?', :president).order(:political_office) }

  def state_enum
    ["ac",
    "al",
    "ap",
    "am",
    "ba",
    "ce",
    "df",
    "es",
    "go",
    "ma",
    "mt",
    "ms",
    "mg",
    "pa",
    "pb",
    "pr",
    "pe",
    "pi",
    "rj",
    "rn",
    "rs",
    "ro",
    "rr",
    "sc",
    "sp",
    "se",
    "to"]
  end

  def political_office_enum
    ['mayor', 'city_councilman', 'state_representative', 'governor', 'congressman', 'senator', 'president']
  end

  def self.search(search, page = 1)
    where("unaccent(name) ilike unaccent(?)", "%#{search}%")
      .order(name: :asc)
      .page(page)
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name

  mount_uploader :image, CategoryImageUploader
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :promise

  validates_presence_of :url, :date
end

app/models/political_party.rb
class PoliticalParty < ActiveRecord::Base
  has_many :candidates
  validates_presence_of :name

  mount_uploader :image, PartyImageUploader
end

app/models/promise.rb
class Promise < ActiveRecord::Base
  belongs_to :candidate
  belongs_to :category
  has_many :links

  validates_presence_of :title, :description, :candidate_id, :category_id, :status, :date
  validates :status, inclusion: {in: :status_enum, allow_nil: true}

  scope :visible, -> { where(visible: true) }
  scope :top_promises, -> { order('up_votes - down_votes') }

  def status_enum
    ['accomplished', 'in_progress', 'not_accomplished']
  end

  def status_enum_i18n
    status_enum.collect{|s| 
      [I18n.t("promises.status.#{s}"), s]
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, :rememberable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end

  def image=(img)
    image = img
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  around_action :redirect_not_found

  private

  def redirect_not_found
    yield
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @candidates = Candidate.search(params[:search], params[:page])
  end

  def show
    @candidate = Candidate.find(params[:id])
    @most_voted = @candidate.promises.visible
                    .order('up_votes - down_votes DESC').limit(5)
    @most_visualized = @candidate.promises.visible
                    .order(visualization_count: :desc).limit(5)

    @promises = @candidate.promises.visible
                    .order(created_at: :desc)
  end

  protected

  def valid_params(params)
    params.require(:candidate).permit(:id)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end

  def about; end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/promises_controller.rb
class PromisesController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def new
    @candidate = Candidate.find params[:candidate_id]
    @promise = @candidate.promises.build
  end

  def create
    @candidate = Candidate.find params[:candidate_id]
    @promise = @candidate.promises.build(promise_params)
    @promise.visible = false

    if @promise.save
      redirect_to @candidate, notice: I18n.t("promises.waiting_approval")
    else
      render "new"
    end
  end

  def show
    @candidate = Candidate.find params[:candidate_id]
    @promise = @candidate.promises.find(params[:id])
    @promise.increment!(:visualization_count)
  end

  def vote_up
    vote(:up_votes)
  end

  def vote_down
    vote(:down_votes)
  end

  private

  def vote(type)
    @candidate = Candidate.find params[:candidate_id]
    @promise = @candidate.promises.find(params[:id])

    if session.has_key?(@promise.id)
      redirect_to candidate_promise_path(@candidate, @promise),
                  alert: I18n.t("promises.already_voted")
    else
      @promise.increment!(type)
      register_vote_in_session
      redirect_to candidate_promise_path(@candidate, @promise),
                  notice: I18n.t("promises.vote_registered")
    end
  end

  def promise_params
    params.require(:promise).
      permit(:title, :description, :category_id, :date, :status)
  end

  def register_vote_in_session
    session[@promise.id] = true
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def show
    @presidents = Candidate.where(:political_office => :president)

    @candidates = Candidate.per_state(params[:state]).page(params[:page])
  end
end

app/controllers/top_promises_controller.rb
class TopPromisesController < ApplicationController
  def index
    @promises = Promise.top_promises.page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def asset_url asset
    "#{request.protocol}#{request.host_with_port}#{asset_path(asset)}"
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/promises_helper.rb
module PromisesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/candidates/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="page-header">
      <h1><%= t('.search-results', search: params[:search]) %></h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul class="media-list">
      <% @candidates.each do |candidate| %>
        <li class="media">
          <%= link_to candidate, :class => 'pull-left' do %>
           <div class="candidate-list-img" style="background-image: url(<%= candidate.image.url %>)"></div>
          <% end %>

          <div class="media-body">
            <h3 class="media-heading text-uppercase">
              <%= link_to candidate.name, candidate %>
            </h3>
            <span class="text-uppercase"><%=t("candidates.political_office.#{candidate.political_office}")%></span>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="text-center">
      <%= paginate @candidates %>
    </div>
  </div>
</div>

app/views/candidates/show.html.erb
<div class="candidate-header">
  <div class="container">
    <div class="col-md-2">
      <div class="candidate-img" style="background-image: url(<%= @candidate.image.url %>)">
      </div>
    </div>
    <div class="col-md-6">
      <h1>
        <%= @candidate.name %>
        <br>
        <span><%=t("candidates.political_office.#{@candidate.political_office}")%></span>
      </h1>
    </div>
    <div class="col-md-4">
      <%= link_to t('.add-promise'), new_candidate_promise_path(@candidate) , title: t('.add-promise'),
        class: 'add-candidate' %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row candidate-info">
    <div class="col-md-12">
      <div class="panel panel-lemon">
        <div class="panel-heading text-uppercase">
          <%= t('.info.about.title') %>
        </div>
        <div class="panel-body">
          <dl class="dl-horizontal">
            <dt><%= t('.info.about.name') %>:</dt>
            <dd><%= @candidate.name %></dd>
            <dt><%= t('.info.about.political_party') %>:</dt>
            <dd><%= @candidate.political_party.name %></dd>
          </dl>
          <p class="bio"><%= @candidate.biography %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="row candidate-proposals">
    <div class="col-md-6">
      <div class="panel panel-blue">
        <div class="panel-heading text-lowercase">
          <%= t('.promises.most-voted') %>
        </div>
        <div class="panel-body">
          <ul>
            <% @most_voted.each do |promise| %>
              <li class="<%=promise.status%>">
                <%= link_to promise.title,
                  candidate_promise_path(@candidate.id, promise.id) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-blue">
        <div class="panel-heading"><%= t('.promises.most-visualized') %></div>
        <div class="panel-body">
          <ul>
            <% @most_visualized.each do |promise| %>
              <li class="<%=promise.status%>">
                <%= link_to promise.title,
                  candidate_promise_path(@candidate.id, promise.id) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row candidate-promises-list">
    <div class="col-md-12">
    <h2 class="promises-list-title">Promises</h2>
      <% unless @promises.empty?  %>
        <ul>
          <% @promises.each do |promise| %>
          <li>
            <div class="promise row">
              <div class="promise-category col-md-2">
                <span class="category-label"><%= promise.category.name %></span>
              </div>
              <div class="box-promise col-md-10">
                <div class="promise-icon"></div>
                  <%= link_to candidate_promise_path(@candidate.id, promise) do %>
                  <h4><%= promise.title %></h4>
                  <p>
                    <%= promise.description %>
                  </p>
                  <% end %>
              </div>
            </div>
          </li>
          <% end %>
        </ul>
      <% else %>
        This profile don't have approved promises. Be the first to <%= link_to "add one", new_candidate_promise_path(@candidate) %>.
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row candidate-comments">
    <div class="col-md-12">
      <h4>Comments</h4>

      <div class="fb-comments" data-href="http://perfilpublico.r14.railsrumble.com" data-numposts="10" data-width="100%" data-colorscheme="light"></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Perfil Público" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "PerfilPublico is a website that focus on giving an overall look about what politicians proposed and what they actually did when they got elected." %>">

    <!-- Facebook -->
    <meta property="og:title" content="Perfil Público"/>
    <meta property="og:site_name" content="Perfil Público"/>
    <meta property="og:url" content="<%= request.original_url %>"/>
    <meta property="og:image" content="<%= asset_url('fb-share.jpg') %>"/>
    <meta property="og:type" content="website"/>
    <meta property="og:description" content="PerfilPublico is a website that focus on giving an overall look about what politicians proposed and what they actually did when they got elected."/>

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,900' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>


    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-13207405-5', 'auto');
      ga('send', 'pageview');

    </script>
  </head>
  <body>

    <header class="header">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <%= link_to root_url, class: "logo-header", title: "Perfil Público"  do %>
              <h1>
                <%= image_tag "logo.png" %>
              </h1>
            <% end %>
            <nav class="menu-nav">
              <ul>
                <li>
                  <%= link_to t('menu.home'), root_path , title: t('menu.home') %>
                </li>
                <li>
                  <%= link_to t('menu.about'), about_path , title: t('menu.about') %>
                </li>
                <li>
                  <%= link_to t('menu.top_promises'), top_promises_path , title: t('menu.top_promises') %>
                </li>
              </ul>
            </nav>
          </div>
          <div class="col-md-4">
            <%= render "components/search_form" %>
          </div>
        </div>
      </div>
    </header>

    <div role="main" class="main-content">
      <% if !flash.empty? %>
        <div class="container">
          <% if flash[:notice] %><div class="alert alert-success"><%= flash[:notice] %></div><% end %>
          <% if flash[:alert] %><div class="alert alert-danger"><%= flash[:alert] %></div><% end %>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <footer class="footer">
      Made with ♥ by crazy brazilian guys
    </footer>
  </body>
</html>

app/views/main/about.html.erb
<div class="container">
  <div class="row">
    <div class="md-col-12 about-project">
      <h2>Perfil Público</h2>

      <p>
        PerfilPublico is a website that focus on giving an overall look about what politicians proposed and what they actually did when they got elected.
      </p>

      <p>
        What we see, election after election, is that most candidates are elected with the same promises that they did before, but never accomplished. With our website, voters may check which of the candidates are actually getting things accomplished and the kind of promises that they are doing.
      </p>

      <p>
        Users may contribute by commenting, choosing which proposals they like or dislike and adding proposals for candidates. Those proposals must contain a link to a video, article or something that proves that the candidate did that promise.
      </p>

      <p>
        For political reasons and since RailsRumble is a programming competition, we decided to use fake data in our demo application. But we will add real data after the competition.
      </p>
    </div>
  </div>
</div>

app/views/promises/_status.html.erb
<%=image_tag "#{promise.status}.png"%>

<%=t("promises.status_info.#{promise.status}")%>

app/views/promises/new.html.erb
<header class="new-promise-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        Hello, <%= current_user.name %> - <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      </div>
    </div>
  </div>
</header>


<div class="container">
  <%= simple_form_for([@candidate, @promise], :html => {:role => "form-horizontal"}) do |f| %>
    <div class="well">
      <%=f.association :category, :collection => Category.order(:name)%>

      <%=f.input :title%>

      <%=f.input :description%>

      <%=f.input :date%>

      <%=f.input :status, :collection => @promise.status_enum_i18n%>

      <div class="form-actions">
        <%= f.button :submit, :class => "btn-primary submit" %>
      </div>
    </div>
  <% end %>
</div>

app/views/promises/show.html.erb
<header class="promise-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2><span class="name"><%=link_to @candidate.name, @candidate%></span> - promises</h2>
      </div>
    </div>
  </div>
</header>

<div class="content-promise">
  <div class="promise-title">
    <div class="container">
      <div class="row">
        <div class="category-icon col-md-1">
          <%= image_tag(@promise.category.image.url(:thumb)) unless @promise.category.image.blank? %>
          <%=@promise.category.name%>
        </div>
        <div class="promise-title-text col-md-11">
          <%=@promise.title%>
        </div>
      </div>
    </div>
  </div>
  <div class="promise-body container">
    <div class="row date-social">
      <div class="col-md-9 promise-info">
        <%=render 'status', :promise => @promise%>
      </div>
      <div class="col-md-3 date">
        <%=l @promise.date, format: :long%>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%=simple_format @promise.description%>

        <div class="links">
          <h4>Links</h4>

          <% if @promise.links.any? %>
            <ul>
              <% @promise.links.each do |link| %>
                <li>
                  <%=link_to link.url, link.url%>
                </li>
              <% end %>
            </ul>
          <% else %>
            <p><%=t('promises.no_links')%></p>
          <% end %>

        </div>
      </div>
    </div>

    <h4>What do you think about this proposal?</h4>

    <div class="row votation">
      <div class="col-md-6">
        <%=link_to '+', vote_up_candidate_promise_path(@candidate, @promise), :class => 'votation-like'%>
        <span class="votation-label-like">Approve <span class="badge"><%=@promise.up_votes.to_i%></span</span>
      </div>
      <div class="col-md-6">
        <%=link_to '+', vote_down_candidate_promise_path(@candidate, @promise), :class => 'votation-not-like'%>
        <span class="votation-label-not-like"><span class="badge"><%=@promise.down_votes.to_i%></span> Disapprove</span>
      </div>
    </div>


    <h4>Comments</h4>

    <div class="fb-comments" data-href="http://perfilpublico.r14.railsrumble.com" data-numposts="10" data-width="100%" data-colorscheme="light"></div>
  </div>
</div>

app/views/states/show.html.erb
<header class="state-header">
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-md-offset-1">
        <div class="state-img" style="">
        </div>
      </div>
      <div class="col-md-9">
        <h3 class="state-name"><%=t("states.#{params[:state]}")%></h3>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <div class="row">
    <div class="col-md-12 candidate-list">
      <% if @presidents.any? %>
        <h3>Presidents</h3>
        <ul>
          <% @presidents.each do |president| %>
            <li>
              <%=link_to president do%>
                <div class="box-image" style="background-image: url(<%= president.image.url %>)"></div>
                <span class="name"><%=president.name%></span>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% end %>

      <% previous_candidate = nil %>

      <% @candidates.each do |candidate| %>
        <% if previous_candidate.try(:political_office) != candidate.political_office %>
          <%='<ul>'.html_safe unless previous_candidate.nil? %>

          <h3><%=t("candidates.political_office.#{candidate.political_office}")%></h3>

          <ul>
        <% end %>

        <li>
          <%=link_to candidate do%>
            <div class="box-image" style="background-image: url(<%= candidate.image.url %>)"></div>
            <span class="name"><%=candidate.name%></span>
          <% end %>
        </li>

        <% previous_candidate = candidate %>
      <% end %>

      </ul>
    </div>
  </div>
</div>

app/views/top_promises/index.html.erb
<header class="top-promises-header">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <h3><%=t('menu.top_promises')%></h3>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <div class="row">
    <div class="col-md-12 top-promises-list">
      <% @promises.each do |promise|%>
        <div class="row top-promise-box">
          <div class="col-md-8 top-promise-title">
            <%=link_to promise.title, candidate_promise_path(promise.candidate, promise) %>
          </div>
          <div class="col-md-4 candidate-context">
            <h3 class="media-heading text-uppercase">
              <%= link_to promise.candidate.name, candidate_path(promise.candidate.id) %>
            </h3>
            <span class="text-uppercase"><%= t promise.candidate.political_office %></span>
          </div>
        </div>
      <% end %>

      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="text-center">
            <%= paginate @promises %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>